name: Bug Report
description: Report an issue witnessed in production.
type: Bug
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what you are seeing happen and where. Include as many details as possible:
        - Any screenshots or error messages
        - A specific link if possible
        - Steps to reproduce
        - Your Device/OS/Browser
    validations:
      required: true
