name: Feature Request
description: Suggest an idea for this project.
type: Request
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: |
        A clear and concise description of what you are requesting. Include as many details as possible:
        - Any screenshots
        - Any links to other issues, resources, or documentation
        - Any other context
    validations:
      required: true
