name: QA Task
description: QA a feature or bug fix
type: QA Task
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please make sure you have assigned the related feature as the parent of this issue.
  - type: textarea
    id: description
    attributes:
      label: Describe the task
      description: |
        A clear and concise description of what and how to QA. Please include:
        - Specific links
        - Steps to take in order to QA the feature or bug fix
        - Any additional notes or contexts
      placeholder: |
        - Go to ...
        - Click ...
    validations:
      required: true
