name: QA Item
description: Fix needed or improvement to a Feature during QA
type: QA Item
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please make sure you have assigned the related issue as the parent of this issue if you are QAing a specific feature or bug.
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: |
        A clear and concise description of what you are seeing happen and where. Include as many details as possible:
        - Any screenshots or error messages
        - A specific link if possible
        - Steps to reproduce
        - Your Device/OS/Browser
    validations:
      required: true
