name: General Task
description: General task that doesn't apply to a specific area.
type: Task
body:
  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: |
        A clear and concise description of what you are seeing happen and where. Include as many details as possible:
        - Any screenshots or error messages
        - A specific link if possible
        - Steps to reproduce
        - Your Device/OS/Browser
    validations:
      required: true
