name: Deploy
description: Collection of issues to be released together from this repository
type: Deploy
title: Deploy repo_name [semver]
body:
  - type: textarea
    id: issues
    attributes:
      label: List of Issues from this Repo
      description: |
        _GH Issues can be closed when linked_
      placeholder: |
        - #XXX
        - #XXX
        - #XXX
  - type: textarea
    id: prs
    attributes:
      label: List of related PRs
      placeholder: |
        - #XXX
        - #XXX
        - #XXX
